config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get 'signup' , to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login' ,to: 'sessions#create'
  delete 'logout' ,to: 'sessions#destroy'
  

  resources :users do
    member do
      get 'edit_basic_info'  #←使わない#
      patch 'update_basic_info'
      get 'attendances/edit_one_month_request'
      patch 'attendances/update_one_month_request'
      get 'attendances/edit_overtime_notice'
      patch 'attendances/update_overtime_notice'
      get 'attendances/edit_one_month_notice'
      patch 'attendances/update_one_month_notice'
      get 'attendances/edit_comp_notice'
      patch 'attendances/update_comp_notice'
      get 'attendances/working'
      get 'attendances/history'
      get 'attendances/output'
    end
    
    #CSV入力#
    collection {post :import}
    
    resources :attendances, only: :update do
      member do
        get 'edit_overtime_request'
        patch 'update_overtime_request'
        patch 'update_comp_request'
      end
      
    end
  end
  
  resources :places 
  
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :attendances, dependent: :destroy
  
  attr_accessor :remember_token
  
  before_save { self.email=email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, presence:true, length:{maximum: 50}
  validates :email, presence:true, length:{maximum:100},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness:true
  
  
  has_secure_password
  validates :password, presence:true, length:{minimum:6}, allow_nil:true
  
  
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  
  
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token=User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remmeber_token)
    return false if remmeber_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest,nil)
  end
  
  
  
  #csvファイルの内容をDBに登録する
  def self.import(file)
    imported_num = 0
  #   #文字コード変換のためにKernel#openとCSV#newを併用
  #   #参考： http://qiita.com/labocho/items/8559576b71642b79df67
    open(file.path,undef: :replace) do |f|
      csv = CSV.new(f, :headers => :first_row) #エラーが出る
      csv.each do |row|
        next if row.header_row?

  #       #CSVの行情報をHASHに変換
        table = Hash[[row.headers, row.fields].transpose]

  #       #登録済みデータ情報
  #       #登録されてなければ作成
        user = find_by(:email=> table['email'])
        if user.nil?
          user= new
        end

  #       #データ情報更新
        user.attributes = table.to_hash.slice(
          *table.to_hash.except(:id, :created_at, :updated_at).keys)

  #       #バリデーションokの場合は保存
        if user.valid?
          user.save!
          imported_num += 1
        end
      end
    end

  #   #更新件数を返却
    imported_num
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit,:update,:destroy]
  before_action :logged_in_user, only:[:index, :show, :edit,:update,:destroy, :update_basic_info] 
  before_action :correct_general_user, only:[:edit, :update]
  before_action :admin_user, only:[:index,:destroy, :update_basic_info]
  before_action :correct_general_or_superior_user, only: :show  
  before_action :set_one_month, only: [:show]
  
  
  def new
    if logged_in?
      flash[:info]="すでにログインしています"
      redirect_to current_user
    end
    @user=User.new
  end
  
  def create
    @user=User.new(user_params)
    if @user.save
      log_in @user
      flash[:success]="新規作成に成功しました"
      redirect_to @user
    else
      render :new
    end
  end
  
  def index
    @users=User.paginate(page:params[:page], per_page:30)
  end
  
  def show
    @worked_sum = @attendances.where.not(started_at:nil).count
    #追記#
    @requested_attendances=Attendance.where(instructor_test:@user.name).where(change:false)  
    @one_month_requested_attendances=Attendance.where(instructor_one_month_test:@user.name).where(change_one_month:false)
    
    #以下、勤怠完全版申請に必要#
    @superior=User.where(superior:true).where.not(id:@user.id)  
    @attendance=@user.attendances.find_by(worked_on:@first_day)
    @comp_requested_attendances=Attendance.where(instructor_comp_test:@user.name).where(change_comp:false)
  end
    
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success]="ユーザー情報を編集しました"
      redirect_to @user
    else
      render :edit
    end
  end
    
  def destroy
    @user.destroy
    flash[:danger]="#{@user.name}を削除しました"
    redirect_to users_url
  end
  
  
  def update_basic_info
    @user=User.find(params[:id])
    if @user.update(basic_info_params)
      flash[:success]="基本情報を編集しました"
    end
    redirect_to users_url
  end
    
  
  
  
  def import
    if params[:csv_file].blank?
      flash[:danger]="読み込むCSVを選択してください"
    else
      num = User.import(params[:csv_file])
      flash[:success]="#{ num.to_s }件のデータ情報を追加/更新しました"
    end
    redirect_to users_url
  end
  
  
  
  
  
  
  
  private  #部署などの基本情報はまだ#
    def user_params
      params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end
    
    
    def basic_info_params
      params.require(:user).permit(:name,:email, :password, :password_confirmation,
      :employee_number, :uid, :affiliation, :basic_work_time, :designated_work_start_time, :designated_work_end_time)
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  
  def format_basic_info(time)
    format("%.2f",((time.hour*60)+time.min)/60.0)
  end
  
  
  def attendance_state(attendance)
    if Date.current==attendance.worked_on
      return '出社' if attendance.started_at.nil?
      return '退社' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    false
  end
  
  
  def overtime_state(attendance)
    if attendance.instructor_test.present? && ! attendance.change?
      return "#{attendance.instructor_test}に残業申請中"
    elsif attendance.change?
      if attendance.instructor_reply==2
        return "残業承認済"
      elsif attendance.instructor_reply==3
        return "残業否認"
      elsif day.instructor_reply==1
        return "#{attendance.instructor_test}に残業申請中"
      else
        return "#{attendance.instructor_test}に残業申請中"
      end
    end
  end
  
  
  
  def one_month_state(attendance)
    if attendance.instructor_one_month_test.present? && ! attendance.change_one_month?
      return "#{attendance.instructor_one_month_test}に勤怠編集申請中"
    elsif attendance.change_one_month?
      if attendance.instructor_one_month_reply==2
        return "勤怠編集承認済"
      elsif attendance.instructor_one_month_reply==3
        return "勤怠編集否認"
      elsif attendance.instructor_one_month_reply==1
        return "#{attendance.instructor_one_month_test}に残業申請中"
      else
        return "#{attendance.instructor_one_month_test}に残業申請中"
      end
    end
  end
  
  
  def comp_state(attendance)
    if attendance.instructor_comp_test.blank? 
      return "所属長承認　未"
    elsif attendance.instructor_comp_test.present? && ! attendance.change_comp?
      return "#{attendance.instructor_comp_test}に勤怠申請中"
    elsif attendance.change_comp?
      if attendance.instructor_comp_reply==2
        return "勤怠承認済"
      elsif attendance.instructor_comp_reply==3
        return "勤怠否認"
      elsif attendance.instructor_comp_reply==1
        return "#{attendance.instructor_comp_test}に勤怠申請中"
      else
        return "#{attendance.instructor_comp_test}に勤怠申請中"
      end
    end
  end
  
  
end

app/views/users/_form.html.erb
<%=form_with(model:@user, local:true) do |f| %>
  <%=render 'shared/error_messages', object:f.object %>
  
  <%=f.label:name, class:"label-#{yield(:class_text)} label-form" %>
  <%=f.text_field:name, class:"form-control" %>
  
  <%=f.label:email,class:"label-#{yield(:class_text)} label-form" %>
  <%=f.email_field:email, class:"form-control" %>
  
  <%=f.label:password, class:"label-#{yield(:class_text)} label-form" %>
  <%=f.password_field:password, class:"form-control" %>
  
  <%=f.label:password_confirmation, class:"label-#{yield(:class_text)} label-form" %>
  <%=f.password_field:password_confirmation, class:"form-control" %>
  
  <%=f.submit yield(:button_text), class:"btn btn-primary btn-block btn-#{yield(:class_text)} btn-form" %>
  
<% end %>

app/views/users/edit.html.erb
<% provide(:title,@user.name) %>
<% provide(:class_text,'user--edit') %>
<% provide(:button_text,'更新') %>

<h1>ユーザー情報の更新</h1>
<div class="row" >
  <div class="col-md-6 col-md-offset-3" >
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<h1>基本情報の修正</h1>

app/views/users/index.html.erb
<% provide(:title,"Users") %>
<h1>ユーザー一覧</h1>

<%= form_tag import_users_path, method: 'post', multipart: true do %>
  <%= file_field_tag :csv_file %>
  <%= submit_tag "CSVをインポート", class:"btn btn-primary btn-csv"  %>
<% end %>

<% @users.each do |user| %>

<% unless current_user?(user) %>
<%=user.name %>
<%=link_to "削除", user_path(user), method: :delete, data: {confirm: "削除しますか？"}, class:"btn btn-primary" %>
<div class="panel-group">
  <div class="panel panel-default">
    <div class="panel-heading">
      <p class="panel-title">
        <a data-toggle="collapse" href="#collapsel<%=user.id %>" class="btn btn-primary btn-lg btn-edit-basic">編集</a>
      </p>
    </div>
    <div id="collapsel<%=user.id %>" class="panel-collapse collapse">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-6 col-md-offset-3" %>
            <%=form_with(model:user, url:update_basic_info_user_path(user), method: :patch, local:true) do |f| %>
              <%=render 'shared/error_messages', object:f.object %>
              
                <%=f.label:name, class:"label-form" %>
                <%=f.text_field:name, class:"form-control" %>
          
                <%=f.label:email, class:"label-form" %>
                <%=f.email_field:email, class:"form-control" %>
                    
                <%=f.label:affiliation, class:"label-form" %>
                <%=f.text_field:affiliation, class:"form-control" %>
          
                <%=f.label:employee_number, class:"label-form" %>
                <%=f.number_field:employee_number, class:"form-control" %>
          
                <%=f.label:uid, class:"label-form" %>
                <%=f.text_field:uid, class:"form-control" %>
          
                <%=f.label:password, class:"label-form" %>
                <%=f.password_field:password, class:"form-control" %>
                    
                <%=f.label:basic_work_time, class:"label-form" %>
                <%=f.time_field:basic_work_time, class:"form-control" %>
          
                <%=f.label:designated_work_start_time, class:"label-form" %>
                <%=f.time_field:designated_work_start_time, class:"form-control" %>
          
                <%=f.label:designated_work_end_time, class:"label-form" %>
                <%=f.time_field:designated_work_end_time, class:"form-control" %>
                    
          
                <%=f.submit:"編集する", class:"btn btn-primary btn-block btn-form" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% end %>

app/views/users/new.html.erb
<% provide(:title,'Signup') %>
<% provide(:class_text,'signup') %>
<% provide(:button_text,'新規作成') %>

<h1>ユーザー登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
  <table class="table table-bordered" id="user-info-table">  <%# trの高さが気になる #%>
    <tbody>
      <tr>
        <td>
        <% if current_user?(@user) %>
          <%=link_to "←", user_path(date:@first_day.prev_month), class: "btn btn-primary btn-change" %>
        <% end %>
          <span class="time-table-title"><%=l(@first_day, format: :middle) %> 時間管理表</span>
        <% if current_user?(@user) %>
          <%=link_to "→", user_path(date:@first_day.next_month), class: "btn btn-primary btn-change" %>
        <% end %>
        </td>
        <td class="designated">
        指定勤務開始時間   <%= l(@user.designated_work_start_time, format: :time) %>
        指定勤務終了時間   <%= l(@user.designated_work_end_time, format: :time) %>
        </td>
        <td colspan="3">基本時間   <%= format_basic_info(@user.basic_work_time) %></td>
        <td>初日   <%=l(@first_day, format: :shortA) %></td>
      </tr>
      <tr>
        <td>所属   <%= @user.affiliation?? @user.affiliation : "未所属" %></td>
        <td>氏名   <%=@user.name %></td>
        <td>コード</td>
        <td>5555</td>
        <td>出勤日数   <%= @worked_sum %>日</td>
        <td>締め   <%=l(@last_day, format: :shortA) %></td>
      </tr>
    </tbody>
  </table>
  <!--上長のページの場合は、以下に申請を見るページへのリンク-->
  <ul class="notice-sentences">
  <% if current_user.superior? && current_user?(@user) %>
    <% if @comp_requested_attendances.count>0 %>
      <li><%=link_to "【所属長承認のお知らせ】", attendances_edit_comp_notice_user_path, remote:true, class:"notice-sentence"%>
      <span class="notice-sentence"><%="#{@comp_requested_attendances.count}件の通知があります" %></span></li>
    <% else %>
      <li class="notice-sentence">【所属長承認のお知らせ】０件の通知があります</li>
    <% end %>
    <% if @one_month_requested_attendances.count>0 %>
      <li><%=link_to "【勤怠編集のお知らせ】", attendances_edit_one_month_notice_user_path, remote:true, class:"notice-sentence"%>
      <span class="notice-sentence"><%="#{@one_month_requested_attendances.count}件の通知があります" %></span></li>
    <% else %>
      <li class="notice-sentence">【勤怠編集のお知らせ】０件の通知があります</li>
    <% end %>
    <% if @requested_attendances.count>0 %>
      <li><%=link_to "【残業申請のお知らせ】", attendances_edit_overtime_notice_user_path, remote:true,class:"notice-sentence"%>
      <span class="notice-sentence"><%="#{@requested_attendances.count}件の通知があります" %></span></li>
    <% else %>
      <li class="notice-sentence">【残業申請のお知らせ】０件の通知があります</li>
    <% end %>
  <% end %>
  </ul>
  <!--ボタン各種-->
  <div class="btn-wrapper">
    <% if current_user?(@user) %>
      <div>
        <%=link_to "勤怠を編集", attendances_edit_one_month_request_user_path(date:@first_day), class: "btn btn-primary" %>
        <%=link_to "csv出力",attendances_output_user_path(date:@first_day, format: :csv), class:"btn btn-primary" %>
      </div>
      <div>
        <%=link_to "勤怠修正ログ(承認済)", attendances_history_user_path(@user), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  
  <table class="table table-bordered table-striped" id="user-attendance-table" >
    <thead>
      <tr>
        <th rowspan="3">残業申請</th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="8">【実績】</th>
        <th colspan="5">所定外勤務</th>
      </tr>
      <tr>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認
          <div class="maru size_small black">
            <div class="letter">印</div>
          </div>
        </th>　
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>
    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <% if current_user?(@user) %>
            <td><%=link_to "残業申請", edit_overtime_request_user_attendance_path(@user, day, date:@first_day), remote:true,class:"btn btn-primary" %></td>
            
          <% else %>
            <td></td>
          <% end %>
          <td><%=l(day.worked_on, format: :short) %></td>
          <td><%=$days_of_the_week[day.worked_on.wday] %></td>
          <td><%=l(day.started_at, format: :hour) if day.started_at.present? %></td>
          <td><%=l(day.started_at, format: :minute) if day.started_at.present? %></td>
          <td>
            <% if current_user?(@user) %>
              <% if btn_text=attendance_state(day) %>
                <%=link_to "#{btn_text}",user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-register" %>
              <% end %>
            <% end %>
          </td>
          <td><%=l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
          <td><%=l(day.finished_at, format: :minute) if day.finished_at.present? %></td>
          <td></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? && ! day.tomorrow_one_month? %>
              <%=str_times=working_times(day.started_at, day.finished_at) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% elsif day.started_at.present? && day.finished_at.present? && day.tomorrow_one_month? %>
              <%=str_times=working_times_tomorrow(day.started_at, day.finished_at) %>
              <% @total_working_times_tomorrow = @total_working_times_tomorrow.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td><%=l(day.scheduled_end_time, format: :hour) if day.scheduled_end_time.present? %></td>
          <td><%=l(day.scheduled_end_time, format: :minute) if day.scheduled_end_time.present? %></td>
          <td>
            <% if day.scheduled_end_time.present? && ! day.tomorrow? %>
              <%=working_times(@user.designated_work_end_time, day.scheduled_end_time) %>
            <% elsif day.scheduled_end_time.present? && day.tomorrow? %>
              <%=working_times_tomorrow(@user.designated_work_end_time, day.scheduled_end_time) %>
            <% end %>
          </td>
          <td><%=day.business_outline %></td>
          <td>
            <% if overtime_text=overtime_state(day) %>
              <%=overtime_text %>
            <% end %>
            <% if one_month_text=one_month_state(day) %>
              <%=one_month_text %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2"></td>
        <td colspan="7"></td>
        <td><%= format("%.2f", @total_working_times.to_f) %></td>
        <td colspan="5"></td>
        <td>
          <% if comp_text=comp_state(@attendance) %>
            <%=comp_text %>
          <% end %>
          <% if current_user?(@user) %>
            <%=form_with(model:@attendance, url:update_comp_request_user_attendance_path(@user, @attendance, date:@first_day), method: :patch, local:true) do |f| %>
            <table class="table table-bordered table-striped">
               <tbody>
                 <td><%= f.collection_select(:instructor_comp_test, @superior,:name, :name,{include_blank:true}, {class: "form-control"}) %></td>
               </tbody>
            </table>
            <%=f.submit "申請", class:"btn btn-primary btn-block"%>
            <% end %>
          <% end %>
        </td>
      </tr>
    </tfoot>
  </table>

<!--モーダルウィンドウ表示-->
<div id="edit-overtime-request" class="modal fade" tabindex="-1" role="dialog" aria-
hidden="true"></div>


<!--モーダルウインドウ表示-->
<div id="edit-overtime-notice" class="modal fade" tabindex="-1" role="dialog" aria-
hidden="true"></div>

<!--モーダルウインドウ表示-->
<div id="edit-one-month-notice" class="modal fade" tabindex="-1" role="dialog" aria-
hidden="true"></div>


<!--モーダルウインドウ表示-->
<div id="edit-comp-notice" class="modal fade" tabindex="-1" role="dialog" aria-
hidden="true"></div>



    