config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get 'signup' , to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login' ,to: 'sessions#create'
  delete 'logout' ,to: 'sessions#destroy'
  

  resources :users do
    member do
      get 'edit_basic_info'  #←使わない#
      patch 'update_basic_info'
      get 'attendances/edit_one_month_request'
      patch 'attendances/update_one_month_request'
      get 'attendances/edit_overtime_notice'
      patch 'attendances/update_overtime_notice'
      get 'attendances/edit_one_month_notice'
      patch 'attendances/update_one_month_notice'
      get 'attendances/edit_comp_notice'
      patch 'attendances/update_comp_notice'
      get 'attendances/working'
      get 'attendances/history'
      get 'attendances/output'
    end
    
    #CSV入力#
    collection {post :import}
    
    resources :attendances, only: :update do
      member do
        get 'edit_overtime_request'
        patch 'update_overtime_request'
        patch 'update_comp_request'
      end
      
    end
  end
  
  resources :places 
  
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  
  
  validates :worked_on, presence:true
  validates :note, length:{maximum:50}
  
  validate :finished_at_is_invalid_without_a_started_at
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at,"が必要です") if started_at.blank? && finished_at.present?
  end
  
  validate :started_at_than_finished_at_fast_if_invalid
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present? && !tomorrow_one_month? && instructor_one_month_test.present?     #上司が入力されていないと時は、申請にならないので、出>退でも構わない#
      errors.add(:started_at, "より早い時間は無効です。") if started_at > finished_at
    end
  end
  
  
  
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  include AttendancesHelper
  
  before_action :set_user, only:[:edit_one_month_request,:update_one_month_request ,:edit_one_month_notice, :update_one_month_notice,
                                 :edit_overtime_notice, :update_overtime_notice,
                                 :edit_comp_notice, :update_comp_notice,
                                 :history, :output]
  before_action :logged_in_user, only:[:update,:edit_one_month_request,:update_one_month_request, :edit_one_month_notice, :update_one_month_notice,
                                       :edit_overtime_request, :update_overtime_request, :edit_overtime_notice, :update_overtime_notice,
                                       :update_comp_request, :edit_comp_notice, :update_comp_notice, 
                                       :working, :history]
  before_action :correct_general_user, only:[:update,:edit_one_month_request,:update_one_month_request, :edit_one_month_notice, :update_one_month_notice,
                                     :edit_overtime_request, :update_overtime_request, :edit_overtime_notice, :update_overtime_notice, 
                                     :update_comp_request, :edit_comp_notice, :update_comp_notice,
                                     :history]
  before_action :admin_user, only:[:working]
  before_action :set_one_month, only:[:edit_one_month_request, :output]
  
  UPDATE_ERROR_MSG="勤怠登録に失敗しました。やり直してください"
  def update
    @user=User.find(params[:user_id])
    @attendance= @user.attendances.find(params[:id])
    if @attendance.before_started_at.nil?
      if @attendance.update(started_at:Time.current.change(sec:0), before_started_at:Time.current.change(sec:0), )
        flash[:info]="おはようございます。"
      else
        flash[:danger]=UPDATE_ERROR_MSG
      end
      
    elsif @attendance.before_finished_at.nil?
      if @attendance.update(finished_at:Time.current.change(sec:0), before_finished_at:Time.current.change(sec:0))
        flash[:info]="お疲れ様でした"
      else
        flash[:danger]=UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  #１か月の勤怠編集を申請するページ#
  def edit_one_month_request
    @superior=User.where(superior:true).where.not(id:current_user.id)
  end
  
  #１か月の勤怠編集の申請内容が送信されるページ#
  def update_one_month_request
      ActiveRecord::Base.transaction do
        if attendance_invalid?
          attendances_params.each do |id, item|
            attendance = Attendance.find(id)
            attendance.update!(item)
            if attendance.change_one_month?
              attendance.update(change_one_month:false)
            end
          end
            flash[:success] = "1ヶ月分の勤怠情報を申請しました。"
            redirect_to user_url(date: params[:date])
        else
          flash[:danger] = "無効な入力データがあった為、申請をキャンセルしました。"
          redirect_to attendances_edit_one_month_request_user_url(date: params[:date])
        end
      end 
  rescue ActiveRecord::RecordInvalid 
    flash[:danger] = "無効な入力データがあった為、申請をキャンセルしました。"
    redirect_to attendances_edit_one_month_request_user_url(date: params[:date])
  end
  
  #１か月の勤怠編集の申請内容を見て承認するページ＃
  def edit_one_month_notice
    @attendances=Attendance.where(instructor_one_month_test:@user.name).where(change_one_month:false)
  end
  
  
  #１か月の勤怠編集の承認内容が送信されるページ#
  def update_one_month_notice
    ActiveRecord::Base.transaction do
      one_month_permit_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.update!(item)
        attendance.update(reply_updated_at:Time.current.change(sec:0))
      end
    end
    flash[:success] = "変更内容を送信しました"
    redirect_to user_url
  rescue ActiveRecord::RecordInvalid 
    flash[:danger] = "無効な入力データがあった為、変更をキャンセルしました。"
    redirect_to attendances_edit_overtime_notice_user_url
  end
  
  
  #残業の申請ページ#
  def edit_overtime_request
    @first_day=params[:date].nil?? Date.current.beginning_of_month : params[:date].to_date
    @user = User.find(params[:user_id])
    @attendance=@user.attendances.find(params[:id])
    @superior=User.where(superior:true).where.not(id:@user.id)
  end
  
  #残業の申請内容が送信されるページ#
  def update_overtime_request
    @user= User.find(params[:user_id])
    @attendance= @user.attendances.find(params[:id])
    if params[:attendance][:scheduled_end_time].blank? || params[:attendance][:business_outline].blank? || params[:attendance][:instructor_test].blank?
      flash[:danger]="無効な入力データがあった為、申請をキャンセルしました"
    else
      @attendance.update(overtime_request_params)
      if @attendance.change?
        @attendance.update(change:false)
      end
      flash[:success]="残業申請を受け付けました"
    end
    redirect_to user_url(@user, date:params[:date])
  end
    
  
  
  #残業の申請内容を見て承認するページ#
  def edit_overtime_notice
    @first_day=params[:date].nil?? Date.current.beginning_of_month : params[:date].to_date
    @attendances=Attendance.where(instructor_test:@user.name).where(change:false)
  end
  
  #残業の承認内容が送信されるページ#
  def update_overtime_notice
    ActiveRecord::Base.transaction do
      overtime_permit_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.update!(item)
      end
    end
    flash[:success] = "変更内容を送信しました"
    redirect_to user_url
  rescue ActiveRecord::RecordInvalid 
    flash[:danger] = "無効な入力データがあった為、変更をキャンセルしました。"
    redirect_to attendances_edit_overtime_notice_user_url
  end
  
  #勤怠完全版申請が送信されるページ#
  def update_comp_request
    @user=User.find(params[:user_id])
    @attendance=@user.attendances.find(params[:id])
    if params[:attendance][:instructor_comp_test].blank?
      flash[:danger]="無効なデータがあった為、申請をキャンセルしました"
    elsif @attendance.update(comp_request_params)
      if @attendance.change_comp?
        @attendance.update(change_comp:false)
      end
      flash[:success]="申請しました"
    end
    redirect_to user_url(@user, date:params[:date])
  end
  
  #勤怠完全版申請を見て承認するページ#
  def edit_comp_notice
    @user=User.find(params[:id])
    @attendances=Attendance.where(instructor_comp_test:@user.name).where(change_comp:false)
  end
  
  
  
  #勤怠完全版承認が送信されるページ#
  def update_comp_notice
    ActiveRecord::Base.transaction do
      comp_permit_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.update!(item)
      end
    end
    flash[:success] = "変更内容を送信しました"
    redirect_to user_url
  rescue ActiveRecord::RecordInvalid 
    flash[:danger] = "無効な入力データがあった為、承認をキャンセルしました。"
    redirect_to attendances_edit_comp_notice_user_url
  end
  
  
  #出勤社員一覧ページ用#
  def working
   @attendances=Attendance.where.not(started_at:nil).where(finished_at:nil)
  end
  
  
  #承認ログページ用#
  def history
    @user=User.find(params[:id])
    # 検索オブジェクト
    @search = @user.attendances.where(instructor_one_month_reply:2).ransack(params[:q])
    # 検索結果
    @attendances = @search.result
  end
  
  
  #以下、CSV出力用#
  def output
    @puts=@attendances.where.not(before_started_at:nil, before_finished_at:nil).or(@attendances.where(instructor_one_month_reply:2))
    respond_to do |format|
      format.html
      format.csv do |csv|
        send_attendances_csv(@puts)
      end
    end
  end

  
  def send_attendances_csv(attendances)
    csv_data = CSV.generate do |csv|
      header = %w(日付 出勤時間 退勤時間)
      csv << header
      @puts.each do |put|
        values = [l(put.worked_on, format: :short), l(put.started_at, format: :time), l(put.finished_at, format: :time)]
        csv << values
      end
    end
    send_data(csv_data, filename: "attendances.csv")
  end
  
  
  

    
  

  private
    def attendances_params
      params.require(:user).permit(attendances:[:started_at, :finished_at, :note, :instructor_one_month_test, :tomorrow_one_month])[:attendances]
    end
    
    def overtime_request_params
      params.require(:attendance).permit(:scheduled_end_time,:business_outline,:tomorrow,:instructor_test)
    end
    
    def overtime_permit_params
      params.require(:user).permit(attendances:[:instructor_reply, :change, :user_id])[:attendances]
    end
    
    def one_month_permit_params
      params.require(:user).permit(attendances:[:instructor_one_month_reply, :change_one_month, :user_id])[:attendances]
    end
    
    def comp_request_params
      params.require(:attendance).permit(:instructor_comp_test)
    end
    
    def comp_permit_params
      params.require(:user).permit(attendances:[:instructor_comp_reply, :change_comp, :user_id])[:attendances]
    end
    
    
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def attendance_state(attendance)
    if Date.current==attendance.worked_on
      return '出社' if attendance.started_at.nil?
      return '退社' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    false
  end

  
  def working_times(start,finish)
    format("%.2f", (((finish-start)/60)/60.0))
  end
  
  def working_times_tomorrow(start,finish)
    format("%.2f", (((finish-start)/60)/60.0)+24)
  end
  
  
  
  
  def attendance_invalid?
    attendances=true
    attendances_params.each do |id, item| 
      if item[:started_at].blank? && item[:finished_at].blank? && item[:instructor_one_month_test].blank?
        next
      elsif item[:started_at].present? && item[:finished_at].present? && item[:instructor_one_month_test].present?
        next
      elsif item[:started_at].present? && item[:finished_at].blank? && item[:instructor_one_month_test].blank?
        next
      elsif item[:started_at].blank? && item[:finished_at].present? && item[:instructor_one_month_test].blank?
        next
      elsif item[:started_at].present? && item[:finished_at].present? && item[:instructor_one_month_test].blank?
        next
      elsif item[:started_at].present? && item[:finished_at].blank? && item[:instructor_one_month_test].present?
        attendances=false
        break
      elsif item[:started_at].blank? && item[:finished_at].present? && item[:instructor_one_month_test].present?
        attendances=false
        break
      elsif item[:started_at].blank? && item[:finished_at].blank? && item[:instructor_one_month_test].present?
        attendances=false
        break
      end
    end
    return attendances
  end
  
  
    
end

app/views/attendances/_edit_comp_notice.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-
			label="Close">
				<span aria-hidden="true">×</span>
			</button>
		</div>
		<div class="modal-body">
			<div class="row">
        <div class="col-md-10 col-md-offset-1">
	        <%= form_with(model:@user, url:attendances_update_comp_notice_user_path(@user), method: :patch, local:true) do |f| %>
	          <% @attendances.each do |day| %>
	          <p class="request-title"><%= "【#{day.user.name}からの勤怠申請】" %></p>
	          <table class="table table-bordered table-condensed" id="comp_notice_table" %>
	            <thead>
	    　        <tr>
	                <th>月</th>
	                <th>指示者確認
	                  <div class="maru size_small black">
	        	          <div class="letter">印</div>
	                  </div>
	                </th>
	                <th>変更</th>
	                <th>勤怠を確認する</th>
	              </tr>
	            </thead>
	            
	            <%=f.fields_for "attendances[]", day do |d| %>
	            <tbody>
	    	         <tr>
	    	           <td><%=l(day.worked_on, format: :shortB) %></td>
	    	　         <!--以下dゾーン-->
	    	　				 <td><%=d.select:instructor_comp_reply,{'なし':1, '承認':2, '否認':3},{include_blank:"申請中"}, {class:"form-control"} %></td>
	    	　				 <td><%=d.check_box :change_comp, id:"change_comp" %></td>
			             <td><%=link_to "勤怠を確認する", user_path(day.user), class:"btn btn-primary"%></td>
	    	         </tr>
	            </tbody>
	           <% end %>
	          </table>
	          <% end %>
	          <%= f.submit "変更を送信する", class:"btn btn-primary" %>
          <% end %>
         </div>
       </div>
     </div>
  </div>
</div>

app/views/attendances/_edit_one_month_notice.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-
			label="Close">
				<span aria-hidden="true">×</span>
			</button>
		</div>
		<div class="modal-body">
			<div class="row">
        <div class="col-md-10 col-md-offset-1">
	        <%= form_with(model:@user, url:attendances_update_one_month_notice_user_path(@user), method: :patch, local:true) do |f| %>
	          <% @attendances.each do |day| %>
	          <p class="request-title"><%= "【#{day.user.name}からの勤怠変更申請】" %></p>
	          <table class="table table-bordered table-striped table-condensed" id="one_month_notice_table" %>
	            <thead>
	    　        <tr>
	                <th rowspan="3">日付</th>
	                <th rowspan="3">曜日</th>
	                <th colspan="4">変更前</th>
	                <th colspan="4">変更後</th>
	                <th rowspan="3">備考</th>
	                <th rowspan="3">指示者確認
	                  <div class="maru size_small black">
	        	          <div class="letter">印</div>
	                  </div>
	                </th>
	                <th rowspan="3">変更</th>
	                <th rowspan="3">勤怠を確認する</th>
	              </tr>
	              <tr>
	                <th colspan="2">出社</th>
	                <th colspan="2">退社</th>
	      	        <th colspan="2">出社</th>
	                <th colspan="2">退社</th>
	              </tr>
	              <tr>
	                <th>時</th>
	                <th>分</th>
	                <th>時</th>
	                <th>分</th>
	                <th>時</th>
	                <th>分</th>
	                <th>時</th>
	                <th>分</th>
	              </tr>
	            </thead>
	    
	            <%=f.fields_for "attendances[]", day do |d| %>
	            <tbody>
	    	         <tr>
	    	           <td><%=l(day.worked_on, format: :short) %></td>
	    	           <td><%=$days_of_the_week[day.worked_on.wday] %></td>
	    	  				 <td><%=l(day.before_started_at, format: :hour) if day.before_started_at.present? %></td>
	    	  				 <td><%=l(day.before_started_at, format: :minute) if day.before_started_at.present?%></td>
	    	　				 <td><%=l(day.before_finished_at, format: :hour) if day.before_finished_at.present? %></td>
	    	　				 <td><%=l(day.before_finished_at, format: :minute) if day.before_finished_at.present?   %></td>
	    	　				 <td><%=l(day.started_at, format: :hour)  %></td>
	    	  				 <td><%=l(day.started_at, format: :minute)  %></td>
	    	　				 <td><%=l(day.finished_at, format: :hour) %></td>
	    	　				 <td><%=l(day.finished_at, format: :minute) %></td>
	    	　				 <td><%=day.note %></td>
	    	　         <!--以下dゾーン-->
	    	　				 <td><%=d.select:instructor_one_month_reply,{'なし':1, '承認':2, '否認':3},{include_blank:"申請中"}, {class:"form-control"} %></td>
	    	　				 <td><%=d.check_box :change_one_month, id:"change_one_month" %></td>
			             <td><%=link_to "勤怠を確認する", user_path(day.user), class:"btn btn-primary"%></td>
	    	         </tr>
	            </tbody>
	           <% end %>
	          </table>
	          <% end %>
	          <%= f.submit "変更を送信する", class:"btn btn-primary" %>
          <% end %>
         </div>
       </div>
     </div>
  </div>
</div>

app/views/attendances/_edit_overtime_notice.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-
			label="Close">
				<span aria-hidden="true">×</span>
			</button>
		</div>
		<div class="modal-body">
			<div class="row">
				<div class="col-md-10 col-md-offset-1">
        <%= form_with(model:@user, url:attendances_update_overtime_notice_user_path(@user), method: :patch, local:true) do |f| %>
          <% @attendances.each do |day| %>
          <p class="request-title"><%= "【#{day.user.name}からの残業申請】" %></p>
          <table class="table table-bordered table-striped table-condensed" id="overtime-notice-table" %>
            <thead>
		          <th>日付</th>
			        <th>曜日</th>
			        <th>終了予定時間</th>
			        <th>指定勤務終了時間</th>
			        <th>時間外時間</th>
			        <th>業務処理内容</th>
			        <th>指示者確認
				        <div class="maru size_small black">
					        <div class="letter">印</div>
				        </div>
			        </th>
			        <th>変更</th>
			        <th>勤務を確認する</th>
		        </thead>
		
		        <%= f.fields_for "attendances[]", day do |d| %>
		        <tbody>
			        <td><%=l(day.worked_on, format: :short) %></td>
			        <td><%=$days_of_the_week[day.worked_on.wday] %></td>
			        <td><%=l(day.scheduled_end_time, format: :time) %></td>
		    	    <td><%=l(day.user.designated_work_end_time, format: :time) %></td>
		 	        <td>
		 	        	<% if day.scheduled_end_time.present? && ! day.tomorrow? %>
		 	        	  <%=working_times(day.user.designated_work_end_time, day.scheduled_end_time) %>
		 	        	<% elsif day.scheduled_end_time.present? && day.tomorrow? %>
		 	        	  <%=working_times_tomorrow(day.user.designated_work_end_time, day.scheduled_end_time) %>
		 	        	<% end %>
		 	        </td>
			        <td><%=day.business_outline %></td>
			        <td><%=d.select:instructor_reply, {'なし':1, '承認':2, '否認':3},{include_blank:"申請中"}, {class:"form-control"} %></td>
			        <td><%=d.check_box :change, id:"change" %></td>
			        <td><%=link_to "勤怠を確認する", user_path(day.user), class:"btn btn-primary"%></td>
			      </tabody>
		        <% end %>
	        </table>
	        <% end %>
	        <%= f.submit "変更を送信する", class:"btn btn-primary" %>
        <% end %>
        </div>
			</div>
		</div>
	</div>
</div>

app/views/attendances/_edit_overtime_request.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-
label="Close">
       <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">【残業申請】</h1>
    </div>
    <div class="modal-body">　　<!--幅調整が必要-->
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <%= form_with(model:@attendance, url: update_overtime_request_user_attendance_path(@user, @attendance, date:@first_day), method: :patch, local:true) do |f| %>
            <table class="table table-bordered table-striped table-condensed" id="overtime-request-table">
              <thead>
                <tr>
                  <th>日付</th>
                  <th>曜日</th>
                  <th>終了予定時間</th>
                  <th>翌日</th>
                  <th>業務処理内容</th>
                  <th>指示者確認
                    <div class="maru size_small black">
                      <div class="letter">印</div>
                    </div>
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><%= l(@attendance.worked_on, format: :short) %></td>
                  <td><%= $days_of_the_week[@attendance.worked_on.wday] %></td>
                  <td><%= f.time_field :scheduled_end_time,class: 'form-control' %></td>
                  <td><%= f.check_box :tomorrow,id: "tomorrow" %></td>
                  <td><%= f.text_field :business_outline, class: 'form-control' %></td>
                  <td><%= f.collection_select(:instructor_test, @superior,:name, :name,{include_blank:true}, {class: "form-control"}) %></td>
                </tr>
              </tbody>
            </table>
          <%= f.submit "変更を送信する", class: "btn btn-block btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/edit_comp_notice.js.erb
$("#edit-comp-notice").html("<%= escape_javascript(render 'edit_comp_notice') %>");
$("#edit-comp-notice").modal("show");

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%=form_with(model:@user, url:attendances_update_one_month_user_path(date:@first_day), method: :patch, local:true) do |f| %>
<table class="table table-bordered table-striped" id="attendance-edit-table">
  <thead>
    <tr>
      <th>日付</th>
      <th>曜日</th>
      <th>出社</th>
      <th>退社</th>
      <th>翌日</th>
      <th>在社時間</th>
      <th>備考</th>
      <th>指示者確認✔︎</th>　<%# 印鑑マーク #%>
    </tr>
  </thead>
  <tbody>
  <% @attendances.each do |day| %>
    <%= f.fields_for "attendances[]", day do |attendance| %>
    <tr>
      <td><%=l(day.worked_on, format: :short) %></td>
      <td><%=$days_of_the_week[day.worked_on.wday] %></td>
      <% if (Date.current<day.worked_on) %>
        <td><%=attendance.time_field:started_at, class:"form-control" ,readonly:true %></td>
        <td><%=attendance.time_field:finished_at, class:"form-control" ,readonly:true %></td>
      <% else %>
        <td><%=attendance.time_field:started_at, class:"form-control"  %></td>
        <td><%=attendance.time_field:finished_at, class:"form-control" %></td>
      <% end %>
      <td></td>
      <td>
        <% if day.started_at.present? && day.finished_at.present? %>
          <%= working_times(day.started_at, day.finished_at) %>
        <% end %>
      </td>
      <td><%= attendance.text_field:note, class:"form-control" %></td>
      <td></td>
    </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<div class="edit-btn-wrapper">
  <%=link_to "キャンセル", user_path(date:@first_day), class:"btn btn-lg btn-primary btn-cancel" %>
  <%=f.submit "編集を保存する", class:"btn btn-lg btn-primary btn-go" %>
</div>
<% end %>

app/views/attendances/edit_one_month_notice.js.erb
$("#edit-one-month-notice").html("<%= escape_javascript(render 'edit_one_month_notice') %>");
$("#edit-one-month-notice").modal("show");

app/views/attendances/edit_one_month_notice_html.erb
<div class="col-md-10 col-md-offset-1">
	<%= form_with(model:@user, url:attendances_update_one_month_notice_user_path(@user), method: :patch, local:true) do |f| %>
	  <% @attendances.each do |day| %>
	  <%= day.user.name %>
	  
	  <table class="table table-bordered table-condensed" id="one_month_notice_table" %>
	    <thead>
	    　<tr>
	        <th>日付</th>
	        <th>曜日</th>
	        <th>変更前</th>
	        <th>変更後</th>
	        <th>備考</th>
	        <th>指示者確認
	          <div class="maru small_size black">
	        	  <div class="letter">印</div>
	          </div>
	        </th>
	        <th>変更</th>
	        <th>勤怠を確認する</th>
	      </tr>
	      <tr>
	        <th>出社</th>
	        <th>退社</th>
	      	<th>出社</th>
	        <th>退社</th>
	      </tr>
	      <tr>
	        <th>時</th>
	        <th>分</th>
	        <th>時</th>
	        <th>分</th>
	        <th>時</th>
	        <th>分</th>
	        <th>時</th>
	        <th>分</th>
	      </tr>
	    </thead>
	    
	    <%=f.fields_for "attendances[]", day do |d| %>
	    <%=d.hidden_field :user_id, :value => day.user.id %>
	    <tbody>
	    	<tr>
	    	  <td><%=l(day.started_at, format: :hour) if day.started_at.present? %></td>
	    	  <td><%=l(day.started_at, format: :minute) if day.started_at.present? %></td>
	    	　<td><%=l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
	    	　<td><%=l(day.finished_at, format: :minute) if day.finished_at.present? %></td>
	    	　
	    	　<td><%=l(day.started_at, format: :hour) if day.started_at.present? %></td>
	    	  <td><%=l(day.started_at, format: :minute) if day.started_at.present? %></td>
	    	　<td><%=l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
	    	　<td><%=l(day.finished_at, format: :minute) if day.finished_at.present? %></td>
	    	　
	    	　<td><%=day.note %></td>
	    	　<!--以下dゾーン-->
	    	　<td><%=d.select:instructor_one_month_reply,{'なし':1, '承認':2, '否認':3},{include_blank:"申請中"}, {class:"form-control"} %></td>
	    	　<td><%=d.check_box :change_one_month, id:"change_one_month" %></td>
			    <td><%=link_to "勤怠を確認する", user_path(day.user), class:"btn btn-primary"%></td>
	    	</tr>
	    </tbody>
	  </table>
	  <% end %>
	  <%= f.submit "変更を送信する", class:"btn btn-primary" %>
  <% end %>
</div>

app/views/attendances/edit_overtime_notice.js.erb
$("#edit-overtime-notice").html("<%= escape_javascript(render 'edit_overtime_notice') %>");
$("#edit-overtime-notice").modal("show");

app/views/attendances/edit_overtime_request.js.erb
$("#edit-overtime-request").html("<%= escape_javascript(render 'edit_overtime_request') %>");
$("#edit-overtime-request").modal("show");

app/views/attendances/working.html.erb
<% provide(:title, "Working") %>
<h1>出勤社員一覧</h1>

<table class="table table-bordered table-striped" id="working-table">
  <thead>
    <tr>
      <th>社員番号</th>
      <th>名前</th>
    </tr>
  </thead>
  <tbody>
  <% @attendances.each do |attendance| %>
    <tr>
      <td><%=attendance.user.employee_number%></td>
      <td><%=attendance.user.name %></td>
    </tr>
  <% end %>
  </tbody>
</table>