config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get 'signup' , to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login' ,to: 'sessions#create'
  delete 'logout' ,to: 'sessions#destroy'
  

  resources :users do
    member do
      get 'edit_basic_info'  #←使わない#
      patch 'update_basic_info'
      get 'attendances/edit_one_month_request'
      patch 'attendances/update_one_month_request'
      get 'attendances/edit_overtime_notice'
      patch 'attendances/update_overtime_notice'
      get 'attendances/edit_one_month_notice'
      patch 'attendances/update_one_month_notice'
      get 'attendances/edit_comp_notice'
      patch 'attendances/update_comp_notice'
      get 'attendances/working'
      get 'attendances/history'
      get 'attendances/output'
    end
    
    #CSV入力#
    collection {post :import}
    
    resources :attendances, only: :update do
      member do
        get 'edit_overtime_request'
        patch 'update_overtime_request'
        patch 'update_comp_request'
      end
      
    end
  end
  
  resources :places 
  
end

app/models/place.rb
class Place < ApplicationRecord
  
  validates :number, presence:true
  validates :name, presence:true
  validates :working_style, presence:true
  
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only:[:edit, :update, :destroy]
  before_action :logged_in_user, only:[:index, :new, :create, :edit, :update, :destroy]
  before_action :admin_user, only:[:index,:new,:create,:edit,:update,:destroy]
  
  
  def index
    @places=Place.all
  end
  
  
  def new
    @place=Place.new
  end
  
  def create
    @place=Place.new(place_params)
    if @place.save
      flash[:success]="新規作成に成功しました"
      redirect_to places_url
    else
      render :new
    end
  end
  
   
   
  def edit
  end
  
  
  def update
    if @place.update(place_params)
     flash[:success]="更新しました"
     redirect_to places_url
    else
      render :edit
    end
  end
  
  
  def destroy
    @place.destroy
    flash[:success]="#{@place.name}を削除しました"
    redirect_to places_url
  end
  
  
  private
    def place_params
      params.require(:place).permit(:number, :name, :working_style)
    end
    
  

end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/edit.html.erb
<% provide(:title, "更新") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3" >

  <%=form_with(model:@place, local:true) do |f| %>
    <%=render 'shared/error_messages', object:f.object %>
  
    <%=f.label:number, class:"label-form" %>
    <%=f.number_field:number, class:"form-control" %>
  
    <%=f.label:name, class:"label-form" %>
    <%=f.text_field:name, class:"form-control" %>
  
    <%=f.label:working_style, class:"label-form" %>
    <%=f.text_field:working_style, class:"form-control" %>
  
    <%=f.submit "更新", class:"btn btn-primary btn-block btn-form" %>
  <% end %>
  </div>
</div>

app/views/places/index.html.erb
<% provide(:title, "Place") %>

<h1>拠点一覧</h1>
<table class="table table-bordered table-striped" id="place-table">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>拠点番号</th>
      <th>拠点名</th>
      <th>勤怠種類</th>
  </thead>
  <tbody>
  <% @places.each do |place| %>
    <tr>
      <td><%=link_to "修正", edit_place_path(place), class:"btn btn-primary btn-edit-place" %></td>
      <td><%=link_to "削除", place_path(place), method: :delete,  data: {confirm: "削除しますか？"}, class:"btn btn-primary" %></td>
      <td><%=place.number %></td>
      <td><%=place.name %></td>
      <td><%=place.working_style %></td>
  <% end %>
  </tbody>
</table>
<div class="jumbotron jumbotron-new-place">
  <%=link_to "拠点情報追加", new_place_path, class:"btn btn-primary btn-new-place" %>
</div>

app/views/places/new.html.erb
<% provide(:title, "新規作成") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%=form_with(model:@place, local:true) do |f| %>
      <%=render 'shared/error_messages', object:f.object %>
  
      <%=f.label:number, class:"label-form" %>
      <%=f.number_field:number, class:"form-control" %>
  
      <%=f.label:name, class:"label-form" %>
      <%=f.text_field:name, class:"form-control" %>
  
      <%=f.label:working_style, class:"label-form" %>
      <%=f.text_field:working_style, class:"form-control" %>
  
      <%=f.submit "新規作成", class:"btn btn-primary btn-block btn-form" %>
  
    <% end %>
  </div>
</div>