config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get 'signup' , to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login' ,to: 'sessions#create'
  delete 'logout' ,to: 'sessions#destroy'
  

  resources :users do
    member do
      get 'edit_basic_info'  #←使わない#
      patch 'update_basic_info'
      get 'attendances/edit_one_month_request'
      patch 'attendances/update_one_month_request'
      get 'attendances/edit_overtime_notice'
      patch 'attendances/update_overtime_notice'
      get 'attendances/edit_one_month_notice'
      patch 'attendances/update_one_month_notice'
      get 'attendances/edit_comp_notice'
      patch 'attendances/update_comp_notice'
      get 'attendances/working'
      get 'attendances/history'
      get 'attendances/output'
    end
    
    #CSV入力#
    collection {post :import}
    
    resources :attendances, only: :update do
      member do
        get 'edit_overtime_request'
        patch 'update_overtime_request'
        patch 'update_comp_request'
      end
      
    end
  end
  
  resources :places 
  
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" >
  <div class="container">
    <%= link_to "勤怠システム",root_path, id:"logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%=link_to "トップへ",root_path, class:"header-list" %></li>
          <% if logged_in? %>
            <% if current_user.admin? %>
              <li><%=link_to "利用者一覧", users_path, class:"header-list" %></li>
              <li><%=link_to "出勤社員一覧", attendances_working_user_path(current_user) %></li>
              <li><%=link_to "拠点一覧", places_path %></li>
              <li><%=link_to "基本情報の修正", edit_basic_info_user_path(current_user), clas:"header-list" %></li>
            <% end %>
            <% unless current_user.admin? %>
            <li class="dropdown">
              <a href='#' class="dropdown-toggle header-list" data-toggle="dropdown" id="dropdown-title">
                アカウント  <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "勤怠表示", current_user %></li>
                <li><%= link_to "設定", edit_user_path(current_user) %></li>
                <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
              </ul>
            </li>
            <% else %>
              <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
            <% end %>
          <% else %>
            <li><%=link_to "ログイン", login_path, class:"header-list" %></li>
          <% end %>
        </ul>
      </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>